resources:
  - name: petclinic-git
    type: git
    source:
      uri: https://github.com/spring-projects/spring-petclinic.git
      branch: master
  # Inception..
  - name: dockerfiles-git
    type: git
    source: 
      uri: https://github.com/xebia/concourse-petclinic.git
      branch: master
  - name: docker-petclinic
    type: docker-image
    source:
      repository: wernerb/petclinic
      email: wernerbuck@gmail.com
      username: wernerb
      password: |
        YOURPASSWORDWITHHOPEFULLYSTRANGECHARS$*@
        
jobs:
- name: build
  plan:
  # Grab resources in parallel
  - aggregate:
    - get: petclinic-git
    - get: dockerfiles-git
  - task: compile
    config:
      platform: linux
      image: "docker:///maven"
      inputs:
      - name: petclinic-git
        path: source
      run:
        path: bash
        args:
          - "-c"
          - mvn -Dmaven.repo.local=$(pwd)/cache -f $(pwd)/source/pom.xml compile
  # - aggregate:
  #   - task: test-java7
  #     config:
  #       platform: linux
  #       image: "docker:///maven#3.3.3-jdk-7"
  #       inputs:
  #       - name: compile
  #         path: .
  #       run:  
  #         path: bash
  #         args: 
  #           - "-c"
  #           - mvn -Dmaven.repo.local=$(pwd)/cache -f $(pwd)/source/pom.xml test
  #   - task: test-java8
  #     config:
  #       platform: linux
  #       image: "docker:///maven#3.3.3-jdk-8"
  #       inputs:
  #       - name: compile
  #         path: .
  #       run:
  #         path: bash
  #         args: 
  #           - "-c"
  #           - mvn -Dmaven.repo.local=$(pwd)/cache -f $(pwd)/source/pom.xml test
  - task: package
    config:
      platform: linux
      image: "docker:///maven"
      inputs:
      - name: dockerfiles-git
        path: dockerfiles
      - name: compile
        path: .
      run:
        path: bash
        args:
          - "-c"
          - mv dockerfiles/docker/Dockerfile $(pwd)/source/ ; mvn -Dmaven.repo.local=$(pwd)/cache -Dmaven.test.skip=true -f $(pwd)/source/pom.xml package

  # reached only after succeeding in all above tests
  - put: docker-petclinic
    params:
      build: package/source

# source/target/petclinic.war
